// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Activity is a trackable activity the user can check in to. CategoryID is
 * nil when the activity belongs to no category (未分类).
 */
export interface Activity {
    "id": number;
    "name": string;
    "color": string;
    "icon": string;
    "categoryId"?: number | null;
    "dailyGoalMinutes": number;
    "sortOrder": number;
    "archived": boolean;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * ActivityStat is a per-activity snapshot for the check-in page.
 */
export interface ActivityStat {
    "activity": Activity;
    "todaySeconds": number;
    "totalSeconds": number;
    "currentStreak": number;
}

/**
 * ActivityTotal is the total recorded time of one activity in a range.
 */
export interface ActivityTotal {
    "activity": Activity;
    "seconds": number;
}

/**
 * BallPosition is the persisted floating-ball window position. Set is false
 * when no position has ever been saved (the frontend then snaps to a default).
 */
export interface BallPosition {
    "x": number;
    "y": number;
    "set": boolean;
}

/**
 * Category is a user-defined group that activities belong to. Activities
 * without a category are shown as "未分类".
 */
export interface Category {
    "id": number;
    "name": string;
    "icon": string;
    "color": string;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * DayBucket aggregates one local day for the stacked bar chart.
 */
export interface DayBucket {
    "date": string;
    "total": number;
    "byActivity": { [_ in string]?: number } | null;
}

/**
 * Entry is one completed check-in (a start/end pair). It may come from the
 * live timer (source "timer") or from manual backfill (source "manual").
 */
export interface Entry {
    "id": number;
    "activityId": number;
    "activityName": string;
    "activityColor": string;
    "startedAt": string;
    "endedAt": string;
    "durationSeconds": number;
    "note": string;
    "source": string;
}

/**
 * EntryFilter narrows the entry list. Dates are local "YYYY-MM-DD" strings;
 * empty strings mean "no bound".
 */
export interface EntryFilter {
    "activityId": number | null;
    "fromDate": string;
    "toDate": string;
    "page": number;
    "pageSize": number;
}

/**
 * EntryList is a page of entries plus the total count for the filter.
 */
export interface EntryList {
    "items": Entry[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

/**
 * MonthBucket aggregates one local month ("YYYY-MM") for the yearly view
 * of the statistics page. Same shape as DayBucket, month granularity.
 */
export interface MonthBucket {
    "month": string;
    "total": number;
    "byActivity": { [_ in string]?: number } | null;
}

/**
 * StreakInfo carries current and longest consecutive check-in days.
 */
export interface StreakInfo {
    "current": number;
    "longest": number;
}

/**
 * StreakRequest selects which streak to compute; nil activity means overall.
 */
export interface StreakRequest {
    "activityId": number | null;
}

/**
 * TimerState describes the at-most-one running timer. The Last* fields are
 * populated only while idle: they carry the paused timer chain (the most
 * recently used activity plus its accumulated seconds) so the UI can show
 * the previous session and offer to resume it.
 */
export interface TimerState {
    "running": boolean;
    "activityId": number;
    "activityName": string;
    "activityColor": string;
    "startedAt": string;
    "elapsedSeconds": number;
    "lastActivityId": number;
    "lastActivityName": string;
    "lastActivityColor": string;
    "lastElapsedSeconds": number;
}
