// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActivityService manages the activity catalog.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Create adds a new activity.
 */
export function Create(a: models$0.Activity): $CancellablePromise<models$0.Activity> {
    return $Call.ByID(451847939, a);
}

/**
 * Delete removes an activity together with all of its entries.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(3888464112, id);
}

/**
 * List returns activities, optionally including archived ones.
 */
export function List(includeArchived: boolean): $CancellablePromise<models$0.Activity[] | null> {
    return $Call.ByID(560692475, includeArchived);
}

/**
 * SetArchived archives or restores an activity.
 */
export function SetArchived(id: number, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(1711304807, id, archived);
}

/**
 * Update modifies an existing activity.
 */
export function Update(a: models$0.Activity): $CancellablePromise<void> {
    return $Call.ByID(2230517106, a);
}
