// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BallService drives the floating ball window and the window-level behaviour
 * around it: toggling the main window, hiding/showing the ball, persisting the
 * ball position and the close-button behaviour. The App/window/Timer fields
 * are injected by main.go after window creation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetAutostart reports whether the app is registered to launch at boot
 * (Windows Run key; false and nil on unsupported platforms).
 */
export function GetAutostart(): $CancellablePromise<boolean> {
    return $Call.ByID(1326740694);
}

/**
 * GetBallPosition returns the persisted ball position; Set is false when no
 * position has ever been saved.
 */
export function GetBallPosition(): $CancellablePromise<models$0.BallPosition> {
    return $Call.ByID(3946672983);
}

/**
 * GetCloseAction returns the stored close-button behaviour. The empty string
 * means "never chosen yet" (treated as CloseActionHide everywhere; the main
 * window prompts the user once in that case).
 */
export function GetCloseAction(): $CancellablePromise<string> {
    return $Call.ByID(2470442449);
}

/**
 * GetGoalNotifyEnabled reports whether the daily-goal notification is on.
 * A missing setting means enabled (the default).
 */
export function GetGoalNotifyEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1239426584);
}

/**
 * GetMainWindowBounds returns the persisted main-window geometry. Set is
 * false when the window has never been moved or resized.
 */
export function GetMainWindowBounds(): $CancellablePromise<models$0.WindowBounds> {
    return $Call.ByID(1838355557);
}

/**
 * HideBall hides the floating ball. When the main window is hidden too, it is
 * shown so the app stays reachable (the tray icon can also restore it).
 */
export function HideBall(): $CancellablePromise<void> {
    return $Call.ByID(3765255486);
}

/**
 * IsBallVisible reports whether the floating ball is currently shown.
 */
export function IsBallVisible(): $CancellablePromise<boolean> {
    return $Call.ByID(3838793044);
}

/**
 * IsQuitting reports whether a real app quit is in progress (used by the
 * close hook to let the quit through without cancelling it).
 */
export function IsQuitting(): $CancellablePromise<boolean> {
    return $Call.ByID(2780432724);
}

/**
 * QuitApp terminates the whole application; the close hook no longer cancels.
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(1554046327);
}

/**
 * SaveBallPosition persists the ball position across restarts, in one
 * transaction so the pair can never be half-written by a crash mid-drag.
 */
export function SaveBallPosition(x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(3758582116, x, y);
}

/**
 * SaveMainWindowBounds persists the main-window geometry across restarts, in
 * one transaction so a crash mid-drag can never leave a mixed geometry (new X
 * with old height).
 */
export function SaveMainWindowBounds(x: number, y: number, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(1767140842, x, y, width, height);
}

/**
 * SetAutostart registers or removes the boot launch entry. Enabling writes
 * the --minimized flag too, so a boot launch starts silently.
 */
export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3432322730, enabled);
}

/**
 * SetCloseAction stores the close-button behaviour ("hide" or "quit").
 */
export function SetCloseAction(action: string): $CancellablePromise<void> {
    return $Call.ByID(3458176909, action);
}

/**
 * SetGoalNotifyEnabled toggles the daily-goal notification.
 */
export function SetGoalNotifyEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3920603236, enabled);
}

/**
 * ShowBall brings the floating ball back (settings page / restore entry).
 */
export function ShowBall(): $CancellablePromise<void> {
    return $Call.ByID(786831215);
}

/**
 * StartMainWindowPersist throttled-saves the main-window bounds whenever it
 * moves or resizes. Safe to call before Run; repeated calls register the
 * handlers only once.
 */
export function StartMainWindowPersist(): $CancellablePromise<void> {
    return $Call.ByID(2442231616);
}

/**
 * StartPositionPersist throttled-saves the ball position whenever the ball
 * window moves (drag or programmatic restore). Safe to call before Run;
 * repeated calls register the handler only once.
 */
export function StartPositionPersist(): $CancellablePromise<void> {
    return $Call.ByID(191844862);
}

/**
 * ToggleMainWindow shows the main window when it is hidden and hides it when
 * it is visible. Returns the resulting visibility.
 */
export function ToggleMainWindow(): $CancellablePromise<boolean> {
    return $Call.ByID(3608196770);
}

/**
 * ToggleTimerFromMenu stops the running timer, or resumes the last one when
 * idle, from the ball's context menu / system tray. TimerService broadcasts
 * timer:started / timer:stopped itself after each successful change, so this
 * wrapper only surfaces failures as a transient toast.
 */
export function ToggleTimerFromMenu(): $CancellablePromise<void> {
    return $Call.ByID(2423215939);
}
