// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BallService drives the floating ball window and the window-level behaviour
 * around it: toggling the main window, hiding/showing the ball, persisting the
 * ball position and the close-button behaviour. The App/window/Timer fields
 * are injected by main.go after window creation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetBallPosition returns the persisted ball position; Set is false when no
 * position has ever been saved.
 */
export function GetBallPosition(): $CancellablePromise<models$0.BallPosition> {
    return $Call.ByID(3946672983);
}

/**
 * GetCloseAction returns the stored close-button behaviour. The empty string
 * means "never chosen yet" (treated as CloseActionHide everywhere; the main
 * window prompts the user once in that case).
 */
export function GetCloseAction(): $CancellablePromise<string> {
    return $Call.ByID(2470442449);
}

/**
 * HideBall hides the floating ball. When the main window is hidden too, it is
 * shown so the app stays reachable (the tray icon can also restore it).
 */
export function HideBall(): $CancellablePromise<void> {
    return $Call.ByID(3765255486);
}

/**
 * IsBallVisible reports whether the floating ball is currently shown.
 */
export function IsBallVisible(): $CancellablePromise<boolean> {
    return $Call.ByID(3838793044);
}

/**
 * IsQuitting reports whether a real app quit is in progress (used by the
 * close hook to let the quit through without cancelling it).
 */
export function IsQuitting(): $CancellablePromise<boolean> {
    return $Call.ByID(2780432724);
}

/**
 * QuitApp terminates the whole application; the close hook no longer cancels.
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(1554046327);
}

/**
 * SaveBallPosition persists the ball position across restarts.
 */
export function SaveBallPosition(x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(3758582116, x, y);
}

/**
 * SetCloseAction stores the close-button behaviour ("hide" or "quit").
 */
export function SetCloseAction(action: string): $CancellablePromise<void> {
    return $Call.ByID(3458176909, action);
}

/**
 * ShowBall brings the floating ball back (settings page / restore entry).
 */
export function ShowBall(): $CancellablePromise<void> {
    return $Call.ByID(786831215);
}

/**
 * StartPositionPersist throttled-saves the ball position whenever the ball
 * window moves (drag or programmatic restore). Safe to call before Run.
 */
export function StartPositionPersist(): $CancellablePromise<void> {
    return $Call.ByID(191844862);
}

/**
 * ToggleMainWindow shows the main window when it is hidden and hides it when
 * it is visible. Returns the resulting visibility.
 */
export function ToggleMainWindow(): $CancellablePromise<boolean> {
    return $Call.ByID(3608196770);
}

/**
 * ToggleTimerFromMenu stops the running timer, or resumes the last one when
 * idle, from the ball's context menu / system tray. The change is broadcast
 * so every window refreshes; failures surface as a transient toast.
 */
export function ToggleTimerFromMenu(): $CancellablePromise<void> {
    return $Call.ByID(2423215939);
}
