// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CategoryService manages the user-defined categories activities belong to.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Create adds a new category.
 */
export function Create(c: models$0.Category): $CancellablePromise<models$0.Category> {
    return $Call.ByID(312475918, c);
}

/**
 * Delete removes a category; its activities become uncategorized.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2571771493, id);
}

/**
 * List returns every category in display order.
 */
export function List(): $CancellablePromise<models$0.Category[] | null> {
    return $Call.ByID(3392108374);
}

/**
 * Update modifies an existing category.
 */
export function Update(c: models$0.Category): $CancellablePromise<void> {
    return $Call.ByID(608244851, c);
}
