// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataService handles backup export and destructive data operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ClearEntries deletes every entry and any running timer state. Activities
 * are kept. A success broadcast lets every window drop its local running
 * state immediately (the cleared timer must not keep ticking in the UI).
 */
export function ClearEntries(): $CancellablePromise<void> {
    return $Call.ByID(477908261);
}

/**
 * DataDir returns the directory holding the SQLite database.
 */
export function DataDir(): $CancellablePromise<string> {
    return $Call.ByID(3777821669);
}

/**
 * ExportCSV writes every entry as CSV (Excel-friendly, with BOM).
 * Returns the written path, or "" when the user cancelled the dialog.
 * Failures are logged via applog before propagating to the frontend toast.
 */
export function ExportCSV(): $CancellablePromise<string> {
    return $Call.ByID(168703372);
}

/**
 * ExportJSON writes the full database (activities + entries) as JSON.
 * Returns the written path, or "" when the user cancelled the dialog.
 * Failures are logged via applog before propagating to the frontend toast.
 */
export function ExportJSON(): $CancellablePromise<string> {
    return $Call.ByID(3533327910);
}

/**
 * OpenDataDir opens the data directory in the platform's file manager.
 */
export function OpenDataDir(): $CancellablePromise<void> {
    return $Call.ByID(1725990917);
}
