// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EntryService handles listing and manual backfill of entries.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateManual records a backfilled entry.
 */
export function CreateManual(activityID: number, startedAt: string, endedAt: string, note: string): $CancellablePromise<models$0.Entry> {
    return $Call.ByID(1140268266, activityID, startedAt, endedAt, note);
}

/**
 * Delete removes an entry.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(3569052291, id);
}

/**
 * List returns a filtered, paginated page of entries.
 */
export function List(f: models$0.EntryFilter): $CancellablePromise<models$0.EntryList> {
    return $Call.ByID(912888544, f);
}

/**
 * Update modifies an existing entry.
 */
export function Update(e: models$0.Entry): $CancellablePromise<void> {
    return $Call.ByID(1646063545, e);
}
