// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetService drives the desktop-pet window and the window-level behaviour
 * around it: toggling the main window, hiding/showing the pet, persisting the
 * pet position and the close-button behaviour. The App/window/Timer fields
 * are injected by main.go after window creation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetAutostart reports whether the app is registered to launch at boot
 * (Windows Run key; false and nil on unsupported platforms).
 */
export function GetAutostart(): $CancellablePromise<boolean> {
    return $Call.ByID(3669708420);
}

/**
 * GetCloseAction returns the stored close-button behaviour. The empty string
 * means "never chosen yet" (treated as CloseActionHide everywhere; the main
 * window prompts the user once in that case).
 */
export function GetCloseAction(): $CancellablePromise<string> {
    return $Call.ByID(2801219259);
}

/**
 * GetGoalNotifyEnabled reports whether the daily-goal notification is on.
 * A missing setting means enabled (the default); only an explicit "0"
 * disables, matching how the notifier itself reads the key.
 */
export function GetGoalNotifyEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(363067486);
}

/**
 * GetMainWindowBounds returns the persisted main-window geometry. Set is
 * false when the window has never been moved or resized.
 */
export function GetMainWindowBounds(): $CancellablePromise<models$0.WindowBounds> {
    return $Call.ByID(480788735);
}

/**
 * GetPetPosition returns the persisted pet position; Set is false when no
 * position has ever been saved.
 */
export function GetPetPosition(): $CancellablePromise<models$0.PetPosition> {
    return $Call.ByID(1762892371);
}

/**
 * HidePet hides the desktop pet. When the main window is hidden too, it is
 * shown so the app stays reachable (the tray icon can also restore it).
 */
export function HidePet(): $CancellablePromise<void> {
    return $Call.ByID(3642376234);
}

/**
 * IsPetVisible reports whether the desktop pet is currently shown.
 */
export function IsPetVisible(): $CancellablePromise<boolean> {
    return $Call.ByID(3797470868);
}

/**
 * IsQuitting reports whether a real app quit is in progress (used by the
 * close hook to let the quit through without cancelling it).
 */
export function IsQuitting(): $CancellablePromise<boolean> {
    return $Call.ByID(3374873982);
}

/**
 * QuitApp terminates the whole application; the close hook no longer cancels.
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(3767805585);
}

/**
 * SaveMainWindowBounds persists the main-window geometry across restarts, in
 * one transaction so a crash mid-drag can never leave a mixed geometry (new X
 * with old height).
 */
export function SaveMainWindowBounds(x: number, y: number, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(532280324, x, y, width, height);
}

/**
 * SavePetPosition persists the pet position across restarts, in one
 * transaction so the pair can never be half-written by a crash mid-drag.
 */
export function SavePetPosition(x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(3966038546, x, y);
}

/**
 * SetAutostart registers or removes the boot launch entry. Enabling writes
 * the --minimized flag too, so a boot launch starts silently.
 */
export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4236962232, enabled);
}

/**
 * SetCloseAction stores the close-button behaviour ("hide" or "quit").
 */
export function SetCloseAction(action: string): $CancellablePromise<void> {
    return $Call.ByID(2707541655, action);
}

/**
 * SetGoalNotifyEnabled toggles the daily-goal notification.
 */
export function SetGoalNotifyEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1876293386, enabled);
}

/**
 * ShowPet brings the desktop pet back (settings page / restore entry).
 */
export function ShowPet(): $CancellablePromise<void> {
    return $Call.ByID(159158793);
}

/**
 * StartMainWindowPersist throttled-saves the main-window bounds whenever it
 * moves or resizes. Safe to call before Run; repeated calls register the
 * handlers only once.
 */
export function StartMainWindowPersist(): $CancellablePromise<void> {
    return $Call.ByID(3847615422);
}

/**
 * StartPositionPersist throttled-saves the pet position whenever the pet
 * window moves (drag or programmatic restore), and emits pet:moving on every
 * move so the front-end can keep its dragging animation in sync. Safe to
 * call before Run; repeated calls register the handler only once.
 */
export function StartPositionPersist(): $CancellablePromise<void> {
    return $Call.ByID(3332322000);
}

/**
 * ToggleMainWindow shows the main window when it is hidden and hides it when
 * it is visible. Returns the resulting visibility.
 */
export function ToggleMainWindow(): $CancellablePromise<boolean> {
    return $Call.ByID(3932652520);
}

/**
 * ToggleTimerFromMenu stops the running timer, or resumes the last one when
 * idle, from the system tray. TimerService broadcasts
 * timer:started / timer:stopped itself after each successful change, so this
 * wrapper only surfaces failures as a transient toast.
 */
export function ToggleTimerFromMenu(): $CancellablePromise<void> {
    return $Call.ByID(3039370349);
}
