// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatsService computes the aggregates shown on the statistics page.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * ActivityTotals returns per-activity totals between two local dates.
 */
export function ActivityTotals(fromDate: string, toDate: string): $CancellablePromise<models$0.ActivityTotal[] | null> {
    return $Call.ByID(3242465429, fromDate, toDate);
}

/**
 * DailyStacked returns per-day totals (with per-activity buckets) between
 * two local dates inclusive.
 */
export function DailyStacked(fromDate: string, toDate: string): $CancellablePromise<models$0.DayBucket[] | null> {
    return $Call.ByID(1306983929, fromDate, toDate);
}

/**
 * Heatmap returns per-day total seconds for the last n days.
 */
export function Heatmap(days: number): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(683221269, days);
}

/**
 * MonthlyStacked returns per-month totals (with per-activity buckets) for the
 * given local year, used by the statistics page's yearly view. Months without
 * data are simply absent; the frontend fills the empty ones.
 */
export function MonthlyStacked(year: number): $CancellablePromise<models$0.MonthBucket[] | null> {
    return $Call.ByID(1864472321, year);
}

/**
 * Overview returns per-activity today totals, all-time totals and current
 * streaks for the check-in page.
 */
export function Overview(): $CancellablePromise<models$0.ActivityStat[] | null> {
    return $Call.ByID(145192428);
}

/**
 * Streaks returns current and longest consecutive check-in days. A nil
 * activity id means across all activities.
 */
export function Streaks(req: models$0.StreakRequest): $CancellablePromise<models$0.StreakInfo> {
    return $Call.ByID(2148158074, req);
}
