// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TimerService owns the at-most-one running timer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetState returns the current timer state (running or idle).
 */
export function GetState(): $CancellablePromise<models$0.TimerState> {
    return $Call.ByID(3943655304);
}

/**
 * Start begins timing the given activity, closing any running timer first
 * (mutual exclusion). Starting the already-running activity is a no-op;
 * starting an idle activity that matches the paused chain resumes it.
 * Broadcasts timer:started only when the state actually changed.
 */
export function Start(activityID: number): $CancellablePromise<models$0.TimerState> {
    return $Call.ByID(56145359, activityID);
}

/**
 * StartLast resumes the timer for the most recently used activity, carrying
 * the accumulated seconds of its earlier sessions forward. It errors when no
 * timer has ever been started (no chain) or the chained activity vanished.
 */
export function StartLast(): $CancellablePromise<models$0.TimerState> {
    return $Call.ByID(354439119);
}

/**
 * Stop ends the running timer and records the entry. Returns nil when the
 * session was too short to record. Broadcasts timer:stopped on success —
 * including discarded short sessions, since the state still became idle.
 */
export function Stop(): $CancellablePromise<models$0.Entry | null> {
    return $Call.ByID(909970325);
}
